import subprocess
import os
import sys
import crypto
import time

def launch_standalone(port=8999):
    """
    Launches the LyricVault backend with a secure token, 
    simulating the lifecycle management a Flutter app would perform.
    """
    # Generate a random token for this session
    # In a real app, this would be generated by the Flutter client
    api_token = "LV_STANDALONE_" + os.urandom(16).hex()
    
    # Path setup
    root_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    python_exe = sys.executable
    backend_script = os.path.join(root_dir, "backend", "main.py")
    
    env = os.environ.copy()
    env["LYRICVAULT_BACKEND_PORT"] = str(port)
    env["LYRICVAULT_API_TOKEN"] = api_token
    env["LYRICVAULT_APP_VERSION"] = "4.5.0-mobile"
    
    print(f"--- LyricVault Standalone Bridge ---")
    print(f"Port:  {port}")
    print(f"Token: {api_token}")
    print(f"--- Launching Backend ---")
    
    try:
        proc = subprocess.Popen(
            [python_exe, backend_script],
            env=env,
            cwd=os.path.join(root_dir, "backend"),
            stdout=sys.stdout,
            stderr=sys.stderr,
            text=True
        )
        
        print("\nBackend is running. Press Ctrl+C to stop.")
        
        while True:
            time.sleep(1)
            if proc.poll() is not None:
                print(f"\nBackend exited with code {proc.returncode}")
                break
                
    except KeyboardInterrupt:
        print("\nShutting down backend...")
        proc.terminate()
        try:
            proc.wait(timeout=5)
        except subprocess.TimeoutExpired:
            proc.kill()
        print("Shutdown complete.")

if __name__ == "__main__":
    # Import crypto for token generation if needed, but os.urandom is safer/simpler
    launch_standalone()
